# Generated by Django 3.0.3 on 2020-12-30 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Title', max_length=100)),
                ('Subtitle', models.CharField(blank=True, default='subtitle', max_length=50, null=True)),
                ('Content', models.TextField(blank=True, default='content', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(choices=[('Marketing', 'Marketing'), ('IT', 'IT'), ('Management', 'Management'), ('PR', 'Public Relations'), ('Finance', 'Finance'), ('HR', 'Human Resource')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Url', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile', models.CharField(max_length=12)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('Division', models.CharField(choices=[('National', 'National'), ('State', 'States'), ('Society', 'Society'), ('Outreach', 'Outreach'), ('Initiative', 'Initiative')], max_length=12)),
                ('City', models.CharField(max_length=20)),
                ('Education', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Graduate', 'Graduate'), ('PostGraduate', 'Post Graduate')], max_length=15)),
                ('InstituteName', models.CharField(max_length=100)),
                ('Std', models.CharField(max_length=3)),
                ('Department', models.CharField(choices=[('Marketing', 'Marketing'), ('IT', 'IT'), ('Management', 'Management'), ('PR', 'Public Relations'), ('Finance', 'Finance'), ('HR', 'Human Resource')], max_length=10)),
                ('WhyHire', models.CharField(max_length=255)),
                ('WhyJoin', models.CharField(max_length=255)),
                ('Timeslot', models.CharField(choices=[('11-1', '11am to 1pm'), ('2-4', '2pm to 4pm'), ('5-7', '5pm to 7pm')], max_length=5)),
                ('Resume', models.FileField(default='', upload_to='resumes')),
                ('IsActive', models.BooleanField(default=False)),
                ('Initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Initiative')),
                ('Outreach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Outreach')),
                ('Position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Position')),
                ('Society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Society')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.State')),
            ],
        ),
    ]
