# Generated by Django 3.0.3 on 2021-01-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='TimeAdded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
