# Generated by Django 3.0.3 on 2021-01-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
